GET http://localhost:5000/v1/user/60063df28719853eb4fd4711
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDYzZGYyODcxOTg1M2ViNGZkNDcxMSIsImlhdCI6MTYxMTE1MTg0NSwiZXhwIjoxNjExMzY3ODQ1fQ.DGiu7VFHkULLWcA3HbaL5jD1UajZQbL2X7d88Kq_Op0