GET http://localhost:5000/v1/user/60089bd240b122d201aa72f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDg5YmQyNDBiMTIyZDIwMWFhNzJmNiIsImlhdCI6MTYxMTE3NzAwMSwiZXhwIjoxNjExMzkzMDAxfQ.3Qcb6JkSLuiH_S4KoaYbfB0jX4L-uEN6LwbMdWc7k3U